//! Default-build purity guard (TASK-005 / ADR 2026-06-01-lucarned-tui-frontend).
//!
//! The interactive `lucarned tui` dashboard lives behind the optional `tui`
//! cargo feature (which implies `remote`). The locked architecture requires the
//! DEFAULT `lucarned` daemon build to stay a pure message bridge: it must link
//! NO `ratatui`/`crossterm` TUI stack and NO rmux binding (`lucarne-rmux` and the
//! `rmux-*` preview SDK crates).
//!
//! This test is the durable regression guard. It shells out to
//! `cargo +nightly tree -Zbuild-dir-new-layout -p lucarned` with NO `--features`
//! and asserts that none of the forbidden crates appear in the dependency tree.
//! `cargo tree` resolves the actual feature-gated dependency graph, so a future
//! change that accidentally pulls the TUI stack into the default build (e.g. a
//! non-optional dep, or `default = ["tui"]`) fails here.
//!
//! `cargo-tree`-based rather than a link-time symbol check because it is
//! deterministic, host-independent, and reads exactly the resolver decision we
//! care about. The release workflow (`release.yml`) is `cargo-dist`-autogenerated
//! and would clobber a hand-added CI step, so the guard lives in the test suite,
//! which runs in every `cargo test` / `cargo test --workspace`.
//!
//! NOTE on what is NOT forbidden: `lucarne-term` (the rmux-FREE terminal
//! vocabulary crate) is a legitimate transitive dependency of other default-build
//! members and must stay allowed. The guard matches the LEFTMOST crate name on
//! each tree line, so `lucarne-term` is never confused with `lucarne-rmux`.

use std::process::Command;

/// Crate names that prove the TUI / rmux stack leaked into the build. Matched as
/// the exact leftmost crate name on a `cargo tree` line (see `tree_crate_names`).
const FORBIDDEN: &[&str] = &[
    "ratatui",
    "ratatui-core",
    "ratatui-crossterm",
    "ratatui-macros",
    "ratatui-widgets",
    "ratatui-rmux",
    "crossterm",
    "lucarne-rmux",
    "rmux-sdk",
    "rmux-types",
    "rmux-proto",
    "rmux-ipc",
    "rmux-os",
];

/// Extract the leftmost crate name from each line of `cargo tree` output.
///
/// `cargo tree` lines look like:
///   `lucarned v0.4.2 (/path)`
///   `├── crossterm v0.29.0`
///   `│   └── ratatui-core v0.1.0 (*)`
/// We strip the leading tree-drawing glyphs/whitespace, then take the first
/// whitespace-delimited token (the crate name).
fn tree_crate_names(output: &str) -> Vec<String> {
    output
        .lines()
        .filter_map(|line| {
            // Drop leading tree glyphs: spaces and the box-drawing set used by cargo.
            let trimmed = line.trim_start_matches(|c: char| {
                c.is_whitespace() || matches!(c, '|' | '`' | '+' | '-' | '├' | '│' | '└' | '─')
            });
            let name = trimmed.split_whitespace().next()?;
            if name.is_empty() {
                None
            } else {
                Some(name.to_string())
            }
        })
        .collect()
}

#[test]
fn default_lucarned_build_links_no_tui_or_rmux_crates() {
    let output = Command::new("cargo")
        .args([
            "+nightly",
            "tree",
            "-Zbuild-dir-new-layout",
            "-p",
            "lucarned",
        ])
        // Explicitly no `--features` / `--all-features`: this is the DEFAULT build.
        .output()
        .expect("failed to run `cargo +nightly tree -Zbuild-dir-new-layout -p lucarned`");

    assert!(
        output.status.success(),
        "cargo tree failed:\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );

    let stdout = String::from_utf8_lossy(&output.stdout);
    let names = tree_crate_names(&stdout);

    let leaked: Vec<&str> = FORBIDDEN
        .iter()
        .copied()
        .filter(|forbidden| names.iter().any(|n| n == forbidden))
        .collect();

    assert!(
        leaked.is_empty(),
        "default `lucarned` build leaked TUI/rmux crates {:?} — the `tui` feature \
         stack must stay optional (implies `remote`) so the default daemon build \
         remains a pure message bridge. Full tree:\n{}",
        leaked,
        stdout,
    );
}

#[test]
fn tree_crate_names_parses_leftmost_name_and_distinguishes_lucarne_term() {
    // Guards the parser itself: `lucarne-term` (rmux-FREE, allowed) must never be
    // read as `lucarne-rmux` (forbidden), and tree glyphs must be stripped.
    let sample = "\
lucarned v0.4.2 (/path)
├── lucarne-term v0.4.2 (/path)
│   └── crossterm v0.29.0 (*)
└── lucarne-rmux v0.4.2 (/path)
";
    let names = tree_crate_names(sample);
    assert!(names.contains(&"lucarned".to_string()));
    assert!(names.contains(&"lucarne-term".to_string()));
    assert!(names.contains(&"crossterm".to_string()));
    assert!(names.contains(&"lucarne-rmux".to_string()));

    // `lucarne-term` is rmux-free and must not be on the forbidden list.
    assert!(!FORBIDDEN.contains(&"lucarne-term"));
    // `lucarne-rmux` is the live rmux binding and must be forbidden.
    assert!(FORBIDDEN.contains(&"lucarne-rmux"));
}
